services:
  iensc-certification-application-db:
    image: mysql:8.0
    container_name: iensc-certification-application-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=d47ac305ae7593831b5fea899e6037907161a5c29d1ed4710a0219ba229f9a95
      - MYSQL_DATABASE=iensc_certification_application_db
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=aa24d32b8b1cfe04a74f668fd58acddbccbe86a9a17a0eff52bb5830e3d1d652
      - MYSQL_PORT=3306
    ports:
      - "3355:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - iensc-certification-application-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: iensc-certification-application-rdbms
    environment:
      - PMA_HOST=iensc-certification-application-db
    ports:
      - "8080:80"
    depends_on:
      - iensc-certification-application-db
    networks:
      - iensc-certification-application-network

volumes:
  db_data:

networks:
  iensc-certification-application-network:
    driver: bridge
