version: '3.8'

services:
  iensc-fingerprint-auth-db:
    image: mysql:8.0
    container_name: iensc-fingerprint-auth-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=0d6b9209fe3bff6cc19455c2699454c286333d67fd7fcf455b2402b97f6971cc
      - MYSQL_DATABASE=ienc-fingerprint-auth-db
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=002f2e8866a27a086dc8a9f744cd8e2b870373e8970b8ca313fdf2767423aef6
      - MYSQL_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - iensc-fingerprint-auth-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql-rdbms
    environment:
      - PMA_HOST=iensc-fingerprint-auth-db
    ports:
      - "8080:80"
    depends_on:
      - iensc-fingerprint-auth-db
    networks:
      - iensc-fingerprint-auth-network

volumes:
  db_data:

networks:
  iensc-fingerprint-auth-network:
    driver: bridge
