import { CertificateServices } from '../../services/certificateServices.js';
import Boom from '@hapi/boom';

/**
 * Controller function to issue a new certificate for a given enrollment.
 * The act/record number is auto-generated by the service.
 *
 * Extracts the new certificate data from the request body, delegates the creation
 * to CertificateServices, and responds according to the outcome.
 * The rotated JWT is not signed here: authAppVerifyToken already generated it upstream,
 * wrote it to the httpOnly 'authentication' cookie, and exposed the same value via
 * res.locals.newUserToken for clients that also need the raw token in the body.
 *
 * @param {Object} req - The Express request object.
 * @param {Object} req.body - The validated request body (see certificateSchema.newCertificateData).
 * @param {string} req.body.issueDate - The issue date.
 * @param {string} req.body.userId - The id of the staff member issuing the certificate.
 * @param {string} req.body.institutionId - The id of the institution.
 * @param {string} req.body.enrollmentId - The id of the enrollment.
 * @param {string} [req.body.recipientId] - The id of the recipient.
 * @param {Object} res - The Express response object.
 * @param {string} res.locals.newUserToken - The rotated JWT set by authAppVerifyToken.
 * @param {Function} next - The next middleware function in the Express.js stack.
 * @returns {Promise<void>} - Sends a JSON response with the operation result and the rotated token.
 */
export const createOneCertificate = async (req, res, next) => {
  const newCertificate = {
    issueDate: req.body.issueDate,
    userId: req.body.userId,
    institutionId: req.body.institutionId,
    enrollmentId: req.body.enrollmentId,
    recipientId: req.body.recipientId,
  };

  const certificateManager = new CertificateServices();

  try {
    const response = await certificateManager.createOne(newCertificate);

    if (response.status === 'CREATED SUCCESSFULLY') {
      return res.status(201).json({
        success: true,
        message: 'Certificado creado exitosamente',
        actNumber: response.actNumber,
        authentication: res.locals.newUserToken,
      });
    }
  } catch (error) {
    const boomError = Boom.boomify(error, {
      message: 'No es posible crear el certificado en la base de datos',
    });
    next(boomError);
  }
};
